language: scala

services:
  - docker

scala:
- 2.12.6

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache
    - project/target
    - target

branches:
  only:
    - master

env:
  global:
    # This forces Python to print everything to stdout/stderr immediately.
    # Otherwise, we've seen issues where all the output from our Travis scripts
    # gets buffered, and only gets printed at the end of the test...
    #
    # ... out of order from the rest of the rest of the output!
    #
    # See also: https://docs.python.org/3/using/cmdline.html#cmdoption-u
    #
    - PYTHONUNBUFFERED=x

jobs:
  include:
   - stage: test
     script:
      - sbt ++$TRAVIS_SCALA_VERSION ";dockerComposeUp;test;dockerComposeStop"

   - stage: check_release_file
     script:
       - python scripts/check_release_file.py

   - stage: release
     script:
       - python scripts/release.py

before_script:
  - openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv -in secrets.zip.enc -out secrets.zip -d
  - unzip secrets.zip;
  - git config user.name "Travis CI on behalf of Wellcome"
  - git config user.email "wellcomedigitalplatform@wellcome.ac.uk"
  - git config core.sshCommand "ssh -i ssh-key/id_rsa"
  - git remote set-url origin "git@github.com:wellcometrust/scala-storage.git"

stages:
 - test
 - name: check_release_file
   if: type = pull_request
 - name: release
   if: type = push
