language: scala

services:
  - docker

scala:
- 2.12.6

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache
    - project/target
    - target

branches:
  only:
    - master

env:
  global:
    # This forces Python to print everything to stdout/stderr immediately.
    - PYTHONUNBUFFERED=x

jobs:
  include:
   - stage: check_release_file
     script:
       - python scripts/check_release_file.py

   - stage: release
     script:
       - python scripts/release.py

before_script:
  - openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv -in secrets.zip.enc -out secrets.zip -d
  - unzip secrets.zip;
  - mkdir -p ~/.aws
  - cp secrets/credentials ~/.aws/credentials
  - git config user.name "Travis CI on behalf of Wellcome"
  - git config user.email "wellcomedigitalplatform@wellcome.ac.uk"
  - git config core.sshCommand "ssh -i ssh-key/id_rsa"
  - git remote set-url origin "git@github.com:wellcometrust/scala-storage.git"

stages:
 # - test
 - name: check_release_file
   if: type = pull_request
 - name: release
   if: type = push
